export const GET_QUESTIONS_INIT = '@survey/GET_QUESTIONS_INIT';
export const GET_QUESTIONS_SUCCESS = '@survey/GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILURE = '@survey/GET_QUESTIONS_FAILURE';

export const SAVE_ANSWER_INIT = '@survey/SAVE_ANSWER_INIT';
