export const GET_QUESTIONS_INIT = '@survey/GET_QUESTIONS_INIT';
export const GET_QUESTIONS_SUCCESS = '@survey/GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILURE = '@survey/GET_QUESTIONS_FAILURE';

export const SAVE_ANSWER_INIT = '@survey/SAVE_ANSWER_INIT';
export const SAVE_ANSWER_SUCCESS = '@survey/SAVE_ANSWER_SUCCESS';
export const SAVE_ANSWER_FAILURE = '@survey/SAVE_ANSWER_FAILURE';
