export const INITIAL_LOAD_INIT = '@locations/INITIAL_LOAD_INIT';
export const INITIAL_LOAD_SUCCESS = '@locations/INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_FAILURE = '@locations/INITIAL_LOAD_FAILURE';

export const GET_SESSIONS_BY_LOCATION_INIT = '@locations/GET_SESSIONS_BY_LOCATION_INIT';
export const GET_SESSIONS_BY_LOCATION_SUCCESS = '@locations/GET_SESSIONS_BY_LOCATION_SUCCESS';
export const GET_SESSIONS_BY_LOCATION_FAILURE = '@locations/GET_SESSIONS_BY_LOCATION_FAILURE';

export const GET_SESSIONS_BY_DATE_INIT = '@locations/GET_SESSIONS_BY_DATE_INIT';
export const GET_SESSIONS_BY_DATE_SUCCESS = '@locations/GET_SESSIONS_BY_DATE_SUCCESS';
export const GET_SESSIONS_BY_DATE_FAILURE = '@locations/GET_SESSIONS_BY_DATE_FAILURE';

export const SET_SELECTED_DATE = '@locations/SET_SELECTED_DATE';
