export const GET_LOCATIONS_INIT = '@locations/GET_LOCATIONS_INIT';
export const GET_LOCATIONS_SUCCESS = '@locations/GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = '@locations/GET_LOCATIONS_FAILURE';

export const VALIDATE_RANGE_AND_SUBMIT_INIT = '@locations/VALIDATE_RANGE_AND_SUBMIT_INIT';
export const VALIDATE_RANGE_AND_SUBMIT_SUCCESS = '@locations/VALIDATE_RANGE_AND_SUBMIT_SUCCESS';
export const VALIDATE_RANGE_AND_SUBMIT_FAILURE = '@locations/VALIDATE_RANGE_AND_SUBMIT_FAILURE';

export const SHOW_OUTSIDE_RANGE_MODAL = '@locations/SHOW_OUTSIDE_RANGE_MODAL';
export const CLOSE_OUTSIDE_RANGE_MODAL = '@locations/CLOSE_OUTSIDE_RANGE_MODAL';

export const GET_SESSIONS_BY_LOCATION_INIT = '@locations/GET_SESSIONS_BY_LOCATION_INIT';
export const GET_SESSIONS_BY_LOCATION_SUCCESS = '@locations/GET_SESSIONS_BY_LOCATION_SUCCESS';
export const GET_SESSIONS_BY_LOCATION_FAILURE = '@locations/GET_SESSIONS_BY_LOCATION_FAILURE';

export const GET_SESSIONS_BY_DATE_INIT = '@locations/GET_SESSIONS_BY_DATE_INIT';
export const GET_SESSIONS_BY_DATE_SUCCESS = '@locations/GET_SESSIONS_BY_DATE_SUCCESS';
export const GET_SESSIONS_BY_DATE_FAILURE = '@locations/GET_SESSIONS_BY_DATE_FAILURE';

export const SET_SELECTED_DATE = '@locations/SET_SELECTED_DATE';
