export const GET_LOCATIONS_INIT = '@locations/GET_LOCATIONS_INIT';
export const GET_LOCATIONS_SUCCESS = '@locations/GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = '@locations/GET_LOCATIONS_FAILURE';

export const GET_SESSIONS_BY_LOCATION_INIT = '@locations/GET_SESSIONS_BY_LOCATION_INIT';
export const GET_SESSIONS_BY_LOCATION_SUCCESS = '@locations/GET_SESSIONS_BY_LOCATION_SUCCESS';
export const GET_SESSIONS_BY_LOCATION_FAILURE = '@locations/GET_SESSIONS_BY_LOCATION_FAILURE';

export const GET_SESSIONS_BY_DATE_INIT = '@locations/GET_SESSIONS_BY_DATE_INIT';
export const GET_SESSIONS_BY_DATE_SUCCESS = '@locations/GET_SESSIONS_BY_DATE_SUCCESS';
export const GET_SESSIONS_BY_DATE_FAILURE = '@locations/GET_SESSIONS_BY_DATE_FAILURE';

export const SET_SELECTED_DATE = '@locations/SET_SELECTED_DATE';
