export const INITIAL_LOAD_INIT = '@sessions/INITIAL_LOAD_INIT';
export const INITIAL_LOAD_SUCCESS = '@sessions/INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_FAILURE = '@sessions/INITIAL_LOAD_FAILURE';

export const INITIAL_LOAD_AUTH_INIT = '@sessions/INITIAL_LOAD_AUTH_INIT';
export const INITIAL_LOAD_AUTH_SUCCESS = '@sessions/INITIAL_LOAD_AUTH_SUCCESS';
export const INITIAL_LOAD_AUTH_FAILURE = '@sessions/INITIAL_LOAD_AUTH_FAILURE';

export const RESERVE_SESSION_INIT = '@sessions/RESERVE_SESSION_INIT';
export const RESERVE_SESSION_SUCCESS = '@sessions/RESERVE_SESSION_SUCCESS';
export const RESERVE_SESSION_FAILURE = '@sessions/RESERVE_SESSION_FAILURE';

export const CANCEL_SESSION_INIT = '@sessions/CANCEL_SESSION_INIT';
export const CANCEL_SESSION_SUCCESS = '@sessions/CANCEL_SESSION_SUCCESS';
export const CANCEL_SESSION_FAILURE = '@sessions/CANCEL_SESSION_FAILURE';

export const CONFIRM_SESSION_INIT = '@sessions/CONFIRM_SESSION_INIT';
export const CONFIRM_SESSION_SUCCESS = '@sessions/CONFIRM_SESSION_SUCCESS';
export const CONFIRM_SESSION_FAILURE = '@sessions/CONFIRM_SESSION_FAILURE';

export const JOIN_SESSION_WAITLIST_INIT = '@sessions/JOIN_SESSION_WAITLIST_INIT';
export const JOIN_SESSION_WAITLIST_SUCCESS = '@sessions/JOIN_SESSION_WAITLIST_SUCCESS';
export const JOIN_SESSION_WAITLIST_FAILURE = '@sessions/JOIN_SESSION_WAITLIST_FAILURE';

export const REMOVE_SESSION_WAITLIST_INIT = '@sessions/REMOVE_SESSION_WAITLIST_INIT';
export const REMOVE_SESSION_WAITLIST_SUCCESS = '@sessions/REMOVE_SESSION_WAITLIST_SUCCESS';
export const REMOVE_SESSION_WAITLIST_FAILURE = '@sessions/REMOVE_SESSION_WAITLIST_FAILURE';

export const SHOW_CANCEL_MODAL = '@sessions/SHOW_CANCEL_MODAL';

export const SIGNUP_BOOK_SESSION = '@sessions/SIGNUP_BOOK_SESSION';
export const BUY_CREDITS_AND_BOOK_SESSION = '@sessions/BUY_CREDITS_AND_BOOK_SESSION';
