import { TAB_QUERY_PARAM } from 'shared/components/Tabs';

import { BILLING_TAB, BIO_TAB } from './tabs';

export default {
  ADS: '/ads',
  CAREERS: '/careers',
  CHECKOUT_CONFIRMED: '/checkout/confirmed',
  CHECKOUT_MEMBERSHIP_CONFIRMED: '/checkout/membership',
  CONTENT: '/content',
  DASHBOARD: '/dashboard',
  FAQ: '/faq',
  FIRSTSESSIONRESERVED: '/first-session/reserved',
  GALLERY: '/gallery',
  HOME: '/',
  LOCATIONS: '/locations',
  LOCATIONSFIRST: '/locations-first',
  LOGIN: '/login',
  MANAGE_MEMBERSHIP: '/manage-membership',
  MEMBER_HANDBOOK: '/crosscourt-member-handbook.pdf',
  MEMBERSHIPS: '/memberships',
  MYACCOUNT: '/my-account',
  NOT_FOUND: '/404',
  ONBOARDING_INTENSITY_LEVEL: '/onboarding/intensity-level',
  ONBOARDING_MEMBERSHIPS: '/onboarding/memberships',
  ONBOARDING_PAYMENT_METHOD: '/onboarding/payment-method',
  ONBOARDING_PERSONAL_DETAILS: '/onboarding/personal-details',
  ONBOARDING_REVIEW: '/onboarding/review',
  PRIVACY_POLICY: '/privacy-policy',
  PWA: '/app',
  REFERRALS: '/my-account/referrals',
  RULES: '/rules',
  SELF_CHECK_IN: '/locations/:id/self-check-in',
  SELF_CHECK_IN_CONFIRM: '/locations/:id/self-check-in/confirm',
  SELF_CHECK_IN_ERROR: '/self-check-in/error',
  SELF_CHECK_IN_SUCCESS: '/self-check-in/success',
  SESSION: '/session/:id/:date',
  SESSIONRESERVED: '/session/reserved',
  SETTINGS: '/settings',
  SETTINGS_BILLING: `/settings?${TAB_QUERY_PARAM}=${BILLING_TAB}`,
  SETTINGS_BIO: `/settings?${TAB_QUERY_PARAM}=${BIO_TAB}`,
  SIGNUP: '/signup',
  SIGNUP_VERIFICATION: '/signup/verification',
  SIGNUP_CONFIRMATION: '/signup/confirmation',
  TERMS: '/terms-and-conditions',
  WHY_JOIN: '/why-join',
};
