export const INITIAL_LOAD_INIT = '@products/INITIAL_LOAD_INIT';
export const INITIAL_LOAD_SUCCESS = '@products/INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_FAILURE = '@products/INITIAL_LOAD_FAILURE';

export const SET_SELECTED_PRODUCT = '@products/SET_SELECTED_PRODUCT';

export const CANCEL_SUBSCRIPTION_INIT = '@subscriptions/CANCEL_SUBSCRIPTION_INIT';
export const CANCEL_SUBSCRIPTION_SUCCESS = '@subscriptions/CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_FAILURE = '@subscriptions/CANCEL_SUBSCRIPTION_FAILURE';

export const REACTIVATE_SUBSCRIPTION_INIT = '@subscriptions/REACTIVATE_SUBSCRIPTION_INIT';
export const REACTIVATE_SUBSCRIPTION_SUCCESS = '@subscriptions/REACTIVATE_SUBSCRIPTION_SUCCESS';
export const REACTIVATE_SUBSCRIPTION_FAILURE = '@subscriptions/REACTIVATE_SUBSCRIPTION_FAILURE';

export const UPDATE_SUBSCRIPTION_PAYMENT_METHOD_INIT =
  '@subscriptions/UPDATE_SUBSCRIPTION_PAYMENT_METHOD_INIT';
export const UPDATE_SUBSCRIPTION_PAYMENT_METHOD_SUCCESS =
  '@subscriptions/UPDATE_SUBSCRIPTION_PAYMENT_METHOD_SUCCESS';
export const UPDATE_SUBSCRIPTION_PAYMENT_METHOD_FAILURE =
  '@subscriptions/UPDATE_SUBSCRIPTION_PAYMENT_METHOD_FAILURE';

export const SUBSCRIPTION_FEEDBACK_INIT = '@subscriptions/SUBSCRIPTION_FEEDBACK_INIT';
export const SUBSCRIPTION_FEEDBACK_SUCCESS = '@subscriptions/SUBSCRIPTION_FEEDBACK_SUCCESS';
export const SUBSCRIPTION_FEEDBACK_FAILURE = '@subscriptions/SUBSCRIPTION_FEEDBACK_FAILURE';

export const PAUSE_SUBSCRIPTION_INIT = '@subscriptions/PAUSE_SUBSCRIPTION_INIT';
export const PAUSE_SUBSCRIPTION_SUCCESS = '@subscriptions/PAUSE_SUBSCRIPTION_SUCCESS';
export const PAUSE_SUBSCRIPTION_FAILURE = '@subscriptions/PAUSE_SUBSCRIPTION_FAILURE';

export const CANCEL_PAUSE_SUBSCRIPTION_INIT = '@subscriptions/CANCEL_PAUSE_SUBSCRIPTION_INIT';
export const CANCEL_PAUSE_SUBSCRIPTION_SUCCESS = '@subscriptions/CANCEL_PAUSE_SUBSCRIPTION_SUCCESS';
export const CANCEL_PAUSE_SUBSCRIPTION_FAILURE = '@subscriptions/CANCEL_PAUSE_SUBSCRIPTION_FAILURE';
