export const INITIAL_LOAD_INIT = '@products/INITIAL_LOAD_INIT';
export const INITIAL_LOAD_SUCCESS = '@products/INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_FAILURE = '@products/INITIAL_LOAD_FAILURE';

export const SET_SELECTED_PRODUCT = '@products/SET_SELECTED_PRODUCT';

export const CANCEL_SUBSCRIPTION_INIT = '@subscriptions/CANCEL_SUBSCRIPTION_INIT';
export const CANCEL_SUBSCRIPTION_SUCCESS = '@subscriptions/CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_FAILURE = '@subscriptions/CANCEL_SUBSCRIPTION_FAILURE';

export const REACTIVE_SUBSCRIPTION_INIT = '@subscriptions/REACTIVE_SUBSCRIPTION_INIT';
export const REACTIVE_SUBSCRIPTION_SUCCESS = '@subscriptions/REACTIVE_SUBSCRIPTION_SUCCESS';
export const REACTIVE_SUBSCRIPTION_FAILURE = '@subscriptions/REACTIVE_SUBSCRIPTION_FAILURE';
