export const INITIAL_LOAD_INIT = '@products/INITIAL_LOAD_INIT';
export const INITIAL_LOAD_SUCCESS = '@products/INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_FAILURE = '@products/INITIAL_LOAD_FAILURE';

export const CANCEL_SUBSCRIPTION_INIT = '@subscriptions/CANCEL_SUBSCRIPTION_INIT';
export const CANCEL_SUBSCRIPTION_SUCCESS = '@subscriptions/CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_FAILURE = '@subscriptions/CANCEL_SUBSCRIPTION_FAILURE';

export const REACTIVATE_SUBSCRIPTION_INIT = '@subscriptions/REACTIVATE_SUBSCRIPTION_INIT';
export const REACTIVATE_SUBSCRIPTION_SUCCESS = '@subscriptions/REACTIVATE_SUBSCRIPTION_SUCCESS';
export const REACTIVATE_SUBSCRIPTION_FAILURE = '@subscriptions/REACTIVATE_SUBSCRIPTION_FAILURE';

export const REMOVE_SUBSCRIPTION_CANCEL_AT_NEXT_PERIOD_END_INIT =
  '@subscriptions/REMOVE_SUBSCRIPTION_CANCEL_AT_NEXT_PERIOD_END_INIT';
export const REMOVE_SUBSCRIPTION_CANCEL_AT_NEXT_PERIOD_END_SUCCESS =
  '@subscriptions/REMOVE_SUBSCRIPTION_CANCEL_AT_NEXT_PERIOD_END_SUCCESS';
export const REMOVE_SUBSCRIPTION_CANCEL_AT_NEXT_PERIOD_END_FAILURE =
  '@subscriptions/REMOVE_SUBSCRIPTION_CANCEL_AT_NEXT_PERIOD_END_FAILURE';

export const UPDATE_SUBSCRIPTION_PAYMENT_METHOD_INIT =
  '@subscriptions/UPDATE_SUBSCRIPTION_PAYMENT_METHOD_INIT';
export const UPDATE_SUBSCRIPTION_PAYMENT_METHOD_SUCCESS =
  '@subscriptions/UPDATE_SUBSCRIPTION_PAYMENT_METHOD_SUCCESS';
export const UPDATE_SUBSCRIPTION_PAYMENT_METHOD_FAILURE =
  '@subscriptions/UPDATE_SUBSCRIPTION_PAYMENT_METHOD_FAILURE';

export const SUBSCRIPTION_REQUEST_CANCELLATION_INIT =
  '@subscriptions/SUBSCRIPTION_REQUEST_CANCELLATION_INIT';
export const SUBSCRIPTION_REQUEST_CANCELLATION_SUCCESS =
  '@subscriptions/SUBSCRIPTION_REQUEST_CANCELLATION_SUCCESS';
export const SUBSCRIPTION_REQUEST_CANCELLATION_FAILURE =
  '@subscriptions/SUBSCRIPTION_REQUEST_CANCELLATION_FAILURE';

export const CANCEL_SUBSCRIPTION_REQUEST_CANCELLATION_INIT =
  '@subscriptions/CANCEL_SUBSCRIPTION_REQUEST_CANCELLATION_INIT';
export const CANCEL_SUBSCRIPTION_REQUEST_CANCELLATION_SUCCESS =
  '@subscriptions/CANCEL_SUBSCRIPTION_REQUEST_CANCELLATION_SUCCESS';
export const CANCEL_SUBSCRIPTION_REQUEST_CANCELLATION_FAILURE =
  '@subscriptions/CANCEL_SUBSCRIPTION_REQUEST_CANCELLATION_FAILURE';

export const PAUSE_SUBSCRIPTION_INIT = '@subscriptions/PAUSE_SUBSCRIPTION_INIT';
export const PAUSE_SUBSCRIPTION_SUCCESS = '@subscriptions/PAUSE_SUBSCRIPTION_SUCCESS';
export const PAUSE_SUBSCRIPTION_FAILURE = '@subscriptions/PAUSE_SUBSCRIPTION_FAILURE';

export const CANCEL_PAUSE_SUBSCRIPTION_INIT = '@subscriptions/CANCEL_PAUSE_SUBSCRIPTION_INIT';
export const CANCEL_PAUSE_SUBSCRIPTION_SUCCESS = '@subscriptions/CANCEL_PAUSE_SUBSCRIPTION_SUCCESS';
export const CANCEL_PAUSE_SUBSCRIPTION_FAILURE = '@subscriptions/CANCEL_PAUSE_SUBSCRIPTION_FAILURE';

export const UNPAUSE_SUBSCRIPTION_INIT = '@subscriptions/UNPAUSE_SUBSCRIPTION_INIT';
export const UNPAUSE_SUBSCRIPTION_SUCCESS = '@subscriptions/UNPAUSE_SUBSCRIPTION_SUCCESS';
export const UNPAUSE_SUBSCRIPTION_FAILURE = '@subscriptions/UNPAUSE_SUBSCRIPTION_FAILURE';
