export const LOGIN_INIT = '@auth/LOGIN_INIT';
export const LOGIN_SUCCESS = '@auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = '@auth/LOGIN_FAILURE';

export const LOGOUT_INIT = '@auth/LOGOUT_INIT';
export const LOGOUT_SUCCESS = '@auth/LOGOUT_SUCCESS';

export const SIGN_UP_INIT = '@auth/SIGN_UP_INIT';
export const SIGN_UP_SUCCESS = '@auth/SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = '@auth/SIGN_UP_FAILURE';

export const SEND_CONFIRMATION_EMAIL_INIT = '@auth/SEND_CONFIRMATION_EMAIL_INIT';
export const SEND_CONFIRMATION_EMAIL_SUCCESS = '@auth/SEND_CONFIRMATION_EMAIL_SUCCESS';
export const SEND_CONFIRMATION_EMAIL_FAILURE = '@auth/SEND_CONFIRMATION_EMAIL_FAILURE';
