export const LOGIN_INIT = '@auth/LOGIN_INIT';
export const LOGIN_SUCCESS = '@auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = '@auth/LOGIN_FAILURE';

export const LOGOUT_INIT = '@auth/LOGOUT_INIT';
export const LOGOUT_SUCCESS = '@auth/LOGOUT_SUCCESS';

export const SIGN_UP_INIT = '@auth/SIGN_UP_INIT';
export const SIGN_UP_SUCCESS = '@auth/SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = '@auth/SIGN_UP_FAILURE';

export const SEND_CONFIRMATION_EMAIL_INIT = '@auth/SEND_CONFIRMATION_EMAIL_INIT';
export const SEND_CONFIRMATION_EMAIL_SUCCESS = '@auth/SEND_CONFIRMATION_EMAIL_SUCCESS';
export const SEND_CONFIRMATION_EMAIL_FAILURE = '@auth/SEND_CONFIRMATION_EMAIL_FAILURE';

export const FORGOT_PASS_INIT = '@auth/FORGOT_PASS_INIT';
export const FORGOT_PASS_SUCCESS = '@auth/FORGOT_PASS_SUCCESS';
export const FORGOT_PASS_FAILURE = '@auth/FORGOT_PASS_FAILURE';

export const PASS_RESET_INIT = '@auth/PASS_RESET_INIT';
export const PASS_RESET_SUCCESS = '@auth/PASS_RESET_SUCCESS';
export const PASS_RESET_FAILURE = '@auth/PASS_RESET_FAILURE';

export const AUTO_LOGIN_INIT = '@auth/AUTO_LOGIN_INIT';
export const AUTO_LOGIN_SUCCESS = '@auth/AUTO_LOGIN_SUCCESS';
export const AUTO_LOGIN_FAILURE = '@auth/AUTO_LOGIN_FAILURE';

export const UPDATE_SKILL_RATING_INIT = '@auth/UPDATE_SKILL_RATING_INIT';
export const UPDATE_SKILL_RATING_SUCCESS = '@auth/UPDATE_SKILL_RATING_SUCCESS';
export const UPDATE_SKILL_RATING_FAILURE = '@auth/UPDATE_SKILL_RATING_FAILURE';
