export const INITIAL_LOAD_INIT = '@myAccount/INITIAL_LOAD_INIT';
export const INITIAL_LOAD_SUCCESS = '@myAccount/INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_FAILURE = '@myAccount/INITIAL_LOAD_FAILURE';

export const EDIT_PROFILE_INIT = '@myAccount/EDIT_PROFILE_INIT';
export const EDIT_PROFILE_SUCCESS = '@myAccount/EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = '@myAccount/EDIT_PROFILE_FAILURE';

export const SHOW_EDIT_PROFILE = '@myAccount/SHOW_EDIT_PROFILE';
