export const INDUSTRIES_AND_OCCUPATIONS = [
  {
    name: 'Office and administrative support',
    occupations: [
      'Receptionist',
      'Teller',
      'Administrative assistant',
      'Information clerk',
      'Customer service representative',
      'Bill and account collector',
      'Financial clerk',
      'Postal service associate',
      'Dispatcher',
    ],
  },
  {
    name: 'Management',
    occupations: [
      'Advertising and marketing manager',
      'Computer information systems manager',
      'Executive',
      'Training and development manager',
      'Sales manager',
      'Natural sciences manager',
      'Hotel manager',
      'Human resources manager',
      'Food services manager',
      'Agricultural manager',
      'Compensation and benefits manager',
    ],
  },
  {
    name: 'Business and financial',
    occupations: [
      'Accountant',
      'Loan officer',
      'Training and development specialist',
      'Personal financial advisor',
      'Management advisor',
      'Claims adjuster',
      'Cost estimator',
      'Financial analyst',
      'Logistician',
      'Purchasing manager',
    ],
  },
  {
    name: 'Architecture and engineering',
    occupations: [
      'Chemical engineer',
      'Aerospace engineer',
      'Cartographer',
      'Civil engineer',
      'Landscape architect',
      'Surveyor',
      'Nuclear engineer',
      'Architect',
      'Drafter',
      'Electrical engineer',
    ],
  },
  {
    name: 'Arts and design',
    occupations: [
      'Fashion designer',
      'Graphic designer',
      'Multimedia artist',
      'Floral designer',
      'Art director',
      'Craft artist',
      'Industrial designer',
    ],
  },
  {
    name: 'Computer and information technology',
    occupations: [
      'Software engineer',
      'Web developer',
      'Computer and information research scientist',
      'Computer network architect',
      'Database administrator',
      'Computer programmer',
      'Information security analyst',
      'Network and computer system administrator',
    ],
  },
  {
    name: 'Education, training and library',
    occupations: [
      'High school teacher',
      'Elementary school teacher',
      'Postsecondary teacher',
      'Teacher assistant',
      'Librarian',
      'Librarian technician',
      'Instructional coordinator',
    ],
  },
  {
    name: 'Healthcare',
    occupations: [
      'Nurse',
      'Dental hygienist',
      'Physician',
      'Surgeon',
      'Physical therapist',
      'Optician',
      'Podiatrist',
      'Veterinarian',
      'Phlebotomist',
      'Medical transcriptionist',
    ],
  },
  {
    name: 'Entertainment and sports',
    occupations: ['Actor', 'Umpire', 'Coach', 'Dancer', 'Musician', 'Producer'],
  },
  { name: 'Legal', occupations: ['Lawyer', 'Judge', 'Court reporter', 'Paralegal', 'Mediator'] },
  {
    name: 'Life, physical and social science',
    occupations: [
      'Anthropologist',
      'Biologist',
      'Chemist',
      'Chemical technician',
      'Historian',
      'Economist',
      'Epidemiologist',
      'Geographer',
      'Urban planner',
    ],
  },
  {
    name: 'Transportation and material moving',
    occupations: [
      'Railroad laborer',
      'Flight attendant',
      'Passenger vehicle driver',
      'Air traffic controller',
      'Pilot',
      'Material mover',
      'Delivery truck driver',
    ],
  },
  {
    name: 'Protective service',
    occupations: [
      'Firefighter',
      'Correctional officer',
      'Fire inspector',
      'Police officer',
      'Security guard',
      'Private detective',
    ],
  },
  {
    name: 'Community and social services',
    occupations: [
      'Social worker',
      'Substance abuse counselor',
      'Probation officer',
      'Marriage and family therapist',
      'Health educator',
      'Rehabilitation counselor',
      'School counselor',
      'Social service assistant',
    ],
  },
  {
    name: 'Sales',
    occupations: [
      'Sales engineer',
      'Cashier',
      'Retail sales associate',
      'Travel agent',
      'Insurance sales agent',
      'Advertising sales agent',
      'Wholesale sales representative',
    ],
  },
];
