export const CREATE_PURCHASE_INIT = '@payments/CREATE_PURCHASE_INIT';
export const CREATE_PURCHASE_SUCCESS = '@payments/CREATE_PURCHASE_SUCCESS';
export const CREATE_PURCHASE_FAILURE = '@payments/CREATE_PURCHASE_FAILURE';

export const CREATE_FREE_SESSION_INIT = '@payments/CREATE_FREE_SESSION_INIT';
export const CREATE_FREE_SESSION_SUCCESS = '@payments/CREATE_FREE_SESSION_SUCCESS';
export const CREATE_FREE_SESSION_FAILURE = '@payments/CREATE_FREE_SESSION_FAILURE';

export const CHECK_PROMO_CODE_INIT = '@payments/CHECK_PROMO_CODE_INIT';
export const CHECK_PROMO_CODE_SUCCESS = '@payments/CHECK_PROMO_CODE_SUCCESS';
export const CHECK_PROMO_CODE_FAILURE = '@payments/CHECK_PROMO_CODE_FAILURE';

export const CLEAR_DISCOUNT = '@payments/CLEAR_DISCOUNT';
