export const CREATE_PURCHASE_INIT = '@checkout/CREATE_PURCHASE_INIT';
export const CREATE_PURCHASE_SUCCESS = '@checkout/CREATE_PURCHASE_SUCCESS';
export const CREATE_PURCHASE_FAILURE = '@checkout/CREATE_PURCHASE_FAILURE';

export const CREATE_SUBSCRIPTION_INIT = '@checkout/CREATE_SUBSCRIPTION_INIT';
export const CREATE_SUBSCRIPTION_SUCCESS = '@checkout/CREATE_SUBSCRIPTION_SUCCESS';
export const CREATE_SUBSCRIPTION_FAILURE = '@checkout/CREATE_SUBSCRIPTION_FAILURE';

export const UPDATE_SUBSCRIPTION_INIT = '@checkout/UPDATE_SUBSCRIPTION_INIT';
export const UPDATE_SUBSCRIPTION_SUCCESS = '@checkout/UPDATE_SUBSCRIPTION_SUCCESS';
export const UPDATE_SUBSCRIPTION_FAILURE = '@checkout/UPDATE_SUBSCRIPTION_FAILURE';

export const CREATE_FREE_SESSION_INIT = '@checkout/CREATE_FREE_SESSION_INIT';
export const CREATE_FREE_SESSION_SUCCESS = '@checkout/CREATE_FREE_SESSION_SUCCESS';
export const CREATE_FREE_SESSION_FAILURE = '@checkout/CREATE_FREE_SESSION_FAILURE';

export const CHECK_PROMO_CODE_INIT = '@checkout/CHECK_PROMO_CODE_INIT';
export const CHECK_PROMO_CODE_SUCCESS = '@checkout/CHECK_PROMO_CODE_SUCCESS';
export const CHECK_PROMO_CODE_FAILURE = '@checkout/CHECK_PROMO_CODE_FAILURE';

export const CLEAR_DISCOUNT = '@checkout/CLEAR_DISCOUNT';

export const SUBSCRIPTION_PRORATE_INIT = '@checkout/SUBSCRIPTION_PRORATE_INIT';
export const SUBSCRIPTION_PRORATE_SUCCESS = '@checkout/SUBSCRIPTION_PRORATE_SUCCESS';
export const SUBSCRIPTION_PRORATE_FAILURE = '@checkout/SUBSCRIPTIONPRORATEK_FAILURE';

export const SHOW_ADD_PAYMENT_METHOD_MODAL = '@checkout/SHOW_ADD_PAYMENT_METHOD_MODAL';
export const CLOSE_ADD_PAYMENT_METHOD_MODAL = '@checkout/CLOSE_ADD_PAYMENT_METHOD_MODAL';

export const SHOW_SELECT_PAYMENT_METHOD_MODAL = '@checkout/SHOW_SELECT_PAYMENT_METHOD_MODAL';
export const CLOSE_SELECT_PAYMENT_METHOD_MODAL = '@checkout/CLOSE_SELECT_PAYMENT_METHOD_MODAL';
