export const GET_QR_DATA_INIT = '@selfCheckIn/GET_QR_DATA_INIT';
export const GET_QR_DATA_SUCCESS = '@selfCheckIn/GET_QR_DATA_SUCCESS';
export const GET_QR_DATA_FAILURE = '@selfCheckIn/GET_QR_DATA_FAILURE';

export const GET_USER_SESSIONS_INIT = '@selfCheckIn/GET_USER_SESSIONS_INIT';
export const GET_USER_SESSIONS_SUCCESS = '@selfCheckIn/GET_USER_SESSIONS_SUCCESS';
export const GET_USER_SESSIONS_FAILURE = '@selfCheckIn/GET_USER_SESSIONS_FAILURE';

export const SELF_CHECK_IN_USER_SESSIONS_INIT = '@selfCheckIn/SELF_CHECK_IN_USER_SESSIONS_INIT';
export const SELF_CHECK_IN_USER_SESSIONS_SUCCESS =
  '@selfCheckIn/SELF_CHECK_IN_USER_SESSIONS_SUCCESS';
export const SELF_CHECK_IN_USER_SESSIONS_FAILURE =
  '@selfCheckIn/SELF_CHECK_IN_USER_SESSIONS_FAILURE';
