export const GET_GALLERY_PHOTOS_INIT = '@gallery/GET_GALLERY_PHOTOS_INIT';
export const GET_GALLERY_PHOTOS_SUCCESS = '@gallery/GET_GALLERY_PHOTOS_SUCCESS';
export const GET_GALLERY_PHOTOS_FAILURE = '@gallery/GET_GALLERY_PHOTOS_FAILURE';
