export const INITIAL_APP_LOAD_INIT = '@app/INITIAL_APP_LOAD_INIT';
export const INITIAL_APP_LOAD_SUCCESS = '@app/INITIAL_APP_LOAD_SUCCESS';
export const INITIAL_APP_LOAD_FAILURE = '@app/INITIAL_APP_LOAD_FAILURE';

export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const SAVE_SESSION_TO_STORAGE = '@app/SAVE_SESSION_TO_STORAGE';
export const SAVE_SESSION_TO_STORAGE_ERROR = '@app/SAVE_SESSION_TO_STORAGE_ERROR';
export const REMOVE_SESSION_FROM_STORAGE = '@app/REMOVE_SESSION_FROM_STORAGE';
export const REMOVE_SESSION_FROM_STORAGE_ERROR = '@app/REMOVE_SESSION_FROM_STORAGE_ERROR';
