export const INITIAL_APP_LOAD_INIT = '@app/INITIAL_APP_LOAD_INIT';
export const INITIAL_APP_LOAD_SUCCESS = '@app/INITIAL_APP_LOAD_SUCCESS';
export const INITIAL_APP_LOAD_FAILURE = '@app/INITIAL_APP_LOAD_FAILURE';
